### ISSUE TITLE
about libsip

### ISSUE THREAD

**Issue by constlhq** [ByteHeathen/libsdp#1]
Sorry for the wrong place, I tried to write to you but gamil told me  `<byteheathen@protonmail.com>: Recipient address rejected: Address does not exist `   I Found libsip will compile successfully with latest nom  6.2.1,  if only change all the trait bound in the lib from ` E: ParseError<&'a [u8]>`  to ` E: ParseError<&'a [u8]> + FromExternalError<&'a [u8], std::io::Error> + FromExternalError<&'a [u8], E>` .You dont have to rewritten entirely for the new nom 6.x version.

**Comment by bytebuddha** [comment]
It's alright, I apologize about the email, I begin working on libsip with a coworker who has control over that email address. I can no longer access it and appears to be deleted (i'm assuming by that error).

I'll assume your right and i was mistaking. I'm in the process of writing a much more detailed note in the libsip repository explaining my reasoning for archiving (some personal, some technical) and leaving a note asking for any future maintainers and contact information to take the crates.io spot, but life just keeps getting in the way.
